void hoshi(act_info* pActwk);
void hoshi_init(act_info* pActwk, act_info* pPlaywk);
void hoshi_move(act_info* pActwk, act_info* pPlaywk);
void kasoku0(act_info* pActwk);
void k0_init(act_info* pActwk, act_info* pPlaywk);
void k0_move(act_info* pActwk, act_info* pPlaywk);
void kasoku(act_info* pActwk);
void kasoku_init(act_info* pActwk, act_info* pPlaywk);
void kasoku_move(act_info* pActwk, act_info* pPlaywk);
